# Generated by Django 5.2 on 2025-04-13 18:51

import django.db.models.deletion
import django_userforeignkey.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha Modif.')),
                ('cedula', models.CharField(blank=True, help_text='Cédula', max_length=20, null=True)),
                ('celular', models.CharField(blank=True, help_text='Número de celular', max_length=10, null=True)),
                ('rol', models.CharField(choices=[('dinamizador', 'Dinamizador'), ('tecnico', 'Técnico(a)'), ('usuario', 'Usuario sena'), ('contratista', 'Contratista'), ('anonimo', 'Anónimo')], default='anonimo', max_length=15, verbose_name='Rol')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='U.creación')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='U.modif.')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha Modif.')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha:')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción:')),
                ('descripcionActual', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción actual')),
                ('placa', models.CharField(blank=True, max_length=12, null=True, verbose_name='Placa')),
                ('placa6', models.CharField(blank=True, max_length=6, null=True, verbose_name='Placa6')),
                ('serial', models.CharField(blank=True, max_length=10, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoElemento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de elemento')),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('discoDuro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Disco duro')),
                ('memoria', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('pantalla', models.CharField(blank=True, max_length=50, null=True)),
                ('procesador', models.CharField(blank=True, max_length=50, null=True)),
                ('unidadLectora', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad lectora')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('sistemaOperativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sistema operativo')),
                ('guayaSeguridad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Guaya de seguridad')),
                ('mouse', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('salon', models.CharField(choices=[('Default', 'Default'), ('406', 'Piso 406'), ('306', 'Piso 2 306'), ('107', 'Piso 1')], default='Default', max_length=15, verbose_name='Salon')),
                ('ubicacion', models.CharField(choices=[('Default', 'Default'), ('406', '-- 406'), ('306', '-- 306'), ('107', '-- 107')], default='Default', max_length=15, verbose_name='Ubicacion')),
                ('numero_registo', models.UUIDField(default=uuid.uuid4)),
                ('type', models.CharField(blank=True, choices=[('escritorio', 'Escritorio'), ('portatil', 'Portatil'), ('impresora', 'Impresora'), ('escaner', 'Escaner'), ('tv', 'Televisor')], max_length=15, null=True, verbose_name='Tipo')),
                ('cuentadanteNumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='N¬identificación')),
                ('status', models.CharField(choices=[('creado', 'Creado'), ('ejecutado', 'Ejecutado'), ('mantenimiento', 'Mantenimiento'), ('facturado', 'Facturado'), ('no_show', 'NO SHOW')], default='creado', max_length=15, verbose_name='Status')),
                ('regional', models.CharField(choices=[('15', 'Boyaca')], default='15', max_length=15, verbose_name='Regional')),
                ('sede', models.CharField(blank=True, choices=[('15', 'Cegafe'), ('16', 'Santa clara'), ('17', 'APE'), ('18', 'ITEDRIS'), ('19', 'Gastronomia')], max_length=15, null=True, verbose_name='Sede')),
                ('attribute', models.CharField(blank=True, max_length=250, null=True, verbose_name='Atributos')),
                ('types', models.CharField(blank=True, choices=[('4', 'Tipo 4')], null=True, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Valor')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='U.creación')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='U.modif.')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.persona', verbose_name='Cuentadante')),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
