# Generated by Django 5.2 on 2025-04-13 18:22

import django.db.models.deletion
import django_userforeignkey.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha Modif.')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('numero_registro', models.UUIDField(default=uuid.uuid4, verbose_name='Número de registro')),
                ('content', models.TextField(blank=True, max_length=500, null=True, verbose_name='Problema a reportar')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Imagen')),
                ('isComputer', models.BooleanField(default=False, verbose_name='Computador')),
                ('isTv', models.BooleanField(default=False, verbose_name='Es TV?')),
                ('isEmail', models.BooleanField(default=False, verbose_name='Es Email?')),
                ('isVideoConferencia', models.BooleanField(default=False, verbose_name='Es video conferencia?')),
                ('isProblemRed', models.BooleanField(default=False, verbose_name='Red')),
                ('isScanner', models.BooleanField(default=False, verbose_name='Escaner')),
                ('isPrinter', models.BooleanField(default=False, verbose_name='Impresora')),
                ('isDb', models.BooleanField(default=False, verbose_name='¿Problema en base de datos?')),
                ('isKeyboard', models.BooleanField(default=False, verbose_name='Teclado')),
                ('isCamera', models.BooleanField(default=False, verbose_name='Cámara')),
                ('isWifi', models.BooleanField(default=False, verbose_name='Wifi')),
                ('isMicrophone', models.BooleanField(default=False, verbose_name='Microfono')),
                ('isMouse', models.BooleanField(default=False, verbose_name='Ratón')),
                ('isFileLost', models.BooleanField(default=False, verbose_name='Archivos perdidos?')),
                ('isLaptopMedical', models.BooleanField(default=False, verbose_name='Equipo en mantenimiento')),
                ('isPantallaAzul', models.BooleanField(default=False, verbose_name='Pantalla azul')),
                ('isPowerOff', models.BooleanField(default=False, verbose_name='No enciende?')),
                ('isAudio', models.BooleanField(default=False, verbose_name='Es Audio?')),
                ('isMantenimiento', models.BooleanField(default=False, verbose_name='Solicita mantenimiento')),
                ('qualification', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Calificacion')),
                ('status', models.CharField(blank=True, choices=[('solicitado', 'solicitado'), ('creado', 'Creado'), ('creado_por', 'Creado por usuario'), ('ejecutado', 'Ejecutado'), ('proceso', 'En proceso'), ('terminado', 'Terminado'), ('noFueNecesario', 'No fue necesario')], default='creado', help_text='Status', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('sede', models.CharField(blank=True, choices=[('15', 'Cegafe'), ('16', 'Santa clara'), ('17', 'APE'), ('18', 'ITEDRIS'), ('19', 'Gastronomia')], max_length=15, null=True, verbose_name='Sede')),
                ('dispositive', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.dispositivo', verbose_name='Equipo tecnológico')),
                ('technic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Técnico(a)')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='U.creación')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='U.modif.')),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
