# Generated by Django 5.2 on 2025-04-14 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_persona_cedula_alter_persona_user'),
        ('srv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='isFileLost',
            field=models.BooleanField(default=False, verbose_name='¿Archivos perdidos?'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='technic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.persona', verbose_name='Técnico(a)'),
        ),
    ]
